parameters:
#    acme_restaurants.example.class: Acme\RestaurantsBundle\Example

services:
#    acme_restaurants.example:
#        class: %acme_restaurants.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
