_welcome:
    pattern:  /welcome
    defaults: { _controller: AcmeDemoBundle:Welcome:index }

_ramona:
    pattern:  /ramona
    defaults: { _controller: AcmeDemoBundle:Welcome:ramona }

_demo_secured:
    resource: "@AcmeDemoBundle/Controller/SecuredController.php"
    type:     annotation

_demo:
    resource: "@AcmeDemoBundle/Controller/DemoController.php"
    type:     annotation
    prefix:   /demo